name: now_chat
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.5.5+10

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  http: ^1.5.0
  uuid: ^4.5.2
  flutter_slidable: ^4.0.3
  logger: ^2.6.2
  flutter_markdown: ^0.7.7+1
  flutter_math_fork: 0.7.3
  url_launcher: ^6.3.2
  markdown: ^7.3.0
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  image_picker: ^1.2.1
  file_picker: ^10.3.2
  cross_file: ^0.3.5
  package_info_plus: ^8.0.2
  archive: ^3.6.1
  crypto: ^3.0.6
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.14.0

flutter:

  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
